const $=id=>document.getElementById(id);
let P=null,month=1,age=16,activities=0,fatigue=0,matchNo=1,offers=[],usedEvents=new Set(),S={fans:1200,rep:50,conf:70,coach:60,college:0,skill:50};
const state={girlfriend:false,careerOver:false};
const colleges=['Alabama','Ohio State','Michigan','Georgia','Texas','USC','Oregon','Penn State','LSU','Florida State','Clemson','Notre Dame'];
const positions={Quarterback:[185,115],RunningBack:[178,105],WideReceiver:[183,100],Cornerback:[180,92],Linebacker:[188,115],DefensiveEnd:[193,125],OffensiveLineman:[193,135],Kicker:[180,95]};
const training=[['Musculation','Tu fais une séance de force.',7,6,10],['Cardio','Tu travailles ton endurance.',5,8,7],['Tapis de course','Tu fais des sprints fractionnés.',6,10,6],['Lancer','Tu répètes tes lancers et ta précision.',9,5,8],['Footwork','Travail explosif des appuis.',8,7,7],['Agilité','Échelle et changements de direction.',7,8,6],['Vidéo tactique','Tu analyses un match.',3,2,9],['Réception','Tu travailles les mains.',8,5,7],['Placages','Séance défensive intense.',7,5,9],['Vitesse','Départs explosifs sur 20 yards.',8,9,5]];
const trainingEvents=[['Le préparateur te félicite','Ton sérieux impressionne le staff.',5,5],['Tu bats ton record','Un nouveau record personnel tombe.',8,4],['Courbatures','Tu dois alléger la prochaine séance.',-1,-3],['Coach particulier','Un ancien pro te donne un conseil précieux.',7,6],['Séance filmée','Une vidéo de ton entraînement circule.',3,5],['Test physique','Tes résultats sont au-dessus de la moyenne.',6,7],['Erreur technique','Le coach corrige un défaut important.',2,6],['Défi avec un coéquipier','Tu acceptes un duel amical.',5,3],['Nouvel équipement','Le lycée te prête du matériel performant.',3,4],['Séance sous la pluie','Conditions difficiles, mais tu progresses.',4,6]];
const dateEvents=[['Pas de petite amie','Tu ne peux pas aller à un rendez-vous romantique.','Il te faut d’abord rencontrer quelqu’un.'],['Premier rendez-vous','Le rendez-vous se passe très bien.',null],['Rendez-vous gênant','Vous n’avez pas vraiment les mêmes centres d’intérêt.',null],['Cinéma','Vous allez voir un film ensemble.',null],['Restaurant','Une longue discussion rapproche votre couple.',null],['Promenade','Une soirée simple et agréable.',null],['Annulation','Ton rendez-vous est annulé au dernier moment.',null],['Déclaration','Ta petite amie te dit qu’elle croit en toi.',null],['Dispute','Une dispute te fait perdre de la confiance.',null],['Réconciliation','Vous discutez et repartez sur de bonnes bases.',null]];
const liveTypes=[['Just Chatting','Tu discutes avec tes abonnés.',5,900],['Gaming','Tu fais un live sur ton jeu préféré.',6,1200],['Analyse football','Tu analyses les matchs NFL.',7,1000],['Q&A','Tes abonnés te posent des questions.',4,800],['Entraînement en direct','Tu montres une partie de ta préparation.',8,1500],['Défi sportif','Tu lances un défi à tes abonnés.',9,2000],['Réaction match','Tu réagis à ton dernier match.',6,1300],['Setup tour','Tu montres ton matériel.',3,700]];
const liveEvents=[['Un streamer connu te raid','Un gros streamer envoie son audience sur ton live.',12,4000],['Clip viral','Un extrait drôle devient viral.',7,3500],['Chat toxique','Des messages agressifs perturbent le live.',-3,500],['Don énorme','Un spectateur fait un gros don.',4,2500],['Invité surprise','Un créateur connu rejoint ton live.',9,3000],['Micro coupé','Tu parles cinq minutes sans savoir que ton micro est coupé.',-2,300],['Serveur en panne','Ton live gaming s’arrête brusquement.',-2,200],['Interview improvisée','Une chaîne sportive reprend ton live.',8,2500],['Challenge réussi','Tu bats un record en direct.',10,3200],['Rumeur démentie','Tu clarifies une rumeur devant ton audience.',5,1800]];
const partyEvents=[['Tu rencontres un recruteur','Un recruteur est présent à la soirée.',8,6],['Photo volée','Une photo de toi circule en ligne.',-2,2],['Tu rentres tôt','Tu protèges ta récupération.',3,5],['Soirée calme','Tu passes un bon moment avec tes amis.',4,1],['Tu dors trop tard','La fatigue monte.',2,-6],['Dispute entre amis','Tu dois calmer le groupe.',2,-2],['DJ célèbre','Un DJ connu te reconnaît.',5,3],['Invitation VIP','Tu rencontres plusieurs personnes influentes.',7,4],['Mauvaise réputation','Un témoin raconte une histoire exagérée.',-5,-3],['Tu refuses l’alcool','Tu gardes ton énergie pour le football.',5,6]];
const vacationEvents=[['Stage sportif','Tu découvres un coach local réputé.',8,5],['Plage','Tu récupères mentalement.',5,4],['Voyage familial','Ta famille te rapproche de tes objectifs.',4,5],['Rencontre internationale','Un jeune joueur te propose de t’entraîner avec lui.',6,4],['Photo de vacances','Une photo attire des fans.',3,7],['Mauvais sommeil','Le voyage perturbe ton rythme.',-2,-3],['Visite d’un stade','Tu assistes à un match universitaire.',5,5],['Découverte culinaire','Tu prends de bonnes habitudes alimentaires.',3,4],['Retour plus motivé','Tes vacances te donnent envie de travailler.',6,7],['Petit pépin de voyage','Une journée est perdue.',-1,-2]];
const randomSeeds=[['Coach','Le coach te demande de prendre un rôle de leader.',6,6],['Média','Un journaliste veut raconter ton parcours.',7,5],['Sponsor','Une petite marque locale te contacte.',5,8],['Rival','Ton rival annonce qu’il veut te battre.',4,3],['Recruteur','Un recruteur universitaire prend des notes pendant ton match.',8,7],['Famille','Ta famille te demande de rester concentré sur l’école.',3,6],['Professeur','Un professeur t’aide à rattraper un devoir.',2,5],['Coéquipier','Un coéquipier te demande des conseils.',4,4],['Fans','Des élèves commencent à te reconnaître dans les couloirs.',3,6],['Réseaux','Une ancienne publication refait surface.',-3,1],['Équipement','Tes chaussures commencent à s’user.',-1,-2],['Transport','Tu arrives en retard à l’entraînement à cause du bus.',-2,-3],['Examens','Les examens te prennent du temps.',-2,3],['Bourse','Une petite aide financière est proposée.',4,4],['Podcast','Un podcast sportif veut t’inviter.',5,6],['Camp','Un camp de recrutement ouvre dans ta région.',8,5],['Rumeur','Une rumeur circule à ton sujet.',-4,-2],['Trophée','Tu es nommé joueur de la semaine.',10,8],['Blessure légère','Une douleur nécessite du repos.',-2,2],['Photographe','Un photographe sportif veut te suivre.',5,4]];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function hideAll(){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hide'));}
function save(){try{localStorage.setItem('rtnfl-save',JSON.stringify({P,month,age,activities,fatigue,matchNo,offers,S,state,used:[...usedEvents]}));}catch(e){}}
function load(){try{const x=JSON.parse(localStorage.getItem('rtnfl-save'));if(!x)return false;({P,month,age,activities,fatigue,matchNo,offers,S}=x);Object.assign(state,x.state||{});usedEvents=new Set(x.used||[]);return !!P;}catch(e){return false;}}
function render(){if(!P)return; $('name').textContent=`${P.first} ${P.last} · ${P.pos}`;$('profile').textContent=`${P.city} · ${P.school} · ${(P.height/100).toFixed(2)} m · ${P.weight} kg · ${P.origin}`;$('date').textContent=`Âge ${age} · Mois ${month} · Match ${matchNo}`;$('fatigue').textContent=fatigue;$('fans').textContent=S.fans.toLocaleString('fr-FR');$('rep').textContent=S.rep;$('conf').textContent=S.conf;$('coach').textContent=S.coach;$('college').textContent=offers.length;save();}
function start(){const first=$('first').value.trim()||'Jayden',last=$('last').value.trim()||'Carter';P={first,last,height:+$('height').value,weight:+$('weight').value,origin:$('origin').value,city:$('city').value,school:$('school').value,pos:$('pos').value};const ideal=positions[P.pos],dh=Math.abs(P.height-ideal[0]),dw=Math.abs(P.weight-ideal[1]);let note='';if(dh<=5&&dw<=15){S.conf+=7;note='✅ Coach : ton gabarit est excellent pour ce poste.'}else if(dh>12||dw>30){S.conf-=7;note='⚠️ Coach : ton gabarit est atypique pour ce poste. Tu devras compenser par ta technique.'}else note='Le coach pense que ton gabarit est exploitable.';$('coachNote').textContent=note;hideAll();$('career').classList.remove('hide');render();hub();}
function hub(){hideAll();$('hub').classList.remove('hide');$('msg').textContent=`${3-activities} activité(s) restante(s) ce mois-ci.`;render();}
function useActivity(name,fn){if(activities>=3){$('msg').textContent='Tu as utilisé tes 3 activités. Passe au mois suivant.';return}activities++;fn();render();}
function trainingMenu(){hideAll();$('activity').classList.remove('hide');$('activityTitle').textContent='🏋️ Entraînement';$('activityText').textContent='Choisis ta séance. Les séances difficiles augmentent la fatigue.';$('activityChoices').innerHTML=training.map((t,i)=>`<button class="choice" data-train="${i}">${t[0]} · +${t[1]} forme</button>`).join('');}
function train(i){const t=training[i];useActivity(t[0],()=>{S.skill+=t[1];S.conf+=t[2]>7?2:1;S.coach+=t[4]>7?2:1;fatigue+=t[2];if(fatigue>80)S.conf-=5;const e=trainingEvents[Math.floor(Math.random()*trainingEvents.length)];showResult(`${t[0]} terminé`,`${e[0]} : ${e[1]}`,()=>hub());});}
function date(){if(!state.girlfriend){showResult('❤️ Rendez-vous',dateEvents[0][1],()=>hub());return}useActivity('Rendez-vous',()=>{const e=dateEvents[1+Math.floor(Math.random()*(dateEvents.length-1))];S.conf+=e[0].includes('Dispute')?-4:3;S.fans+=100;showResult(e[0],e[1],()=>hub());});}
function livestreamMenu(){hideAll();$('activity').classList.remove('hide');$('activityTitle').textContent='📱 Choisir ton livestream';$('activityText').textContent='Quel type de live veux-tu faire ?';$('activityChoices').innerHTML=liveTypes.map((t,i)=>`<button class="choice" data-live="${i}">${t[0]} · environ ${t[3].toLocaleString('fr-FR')} nouveaux points de visibilité</button>`).join('');}
function live(i){const t=liveTypes[i];useActivity('Livestream',()=>{S.rep+=t[2];S.fans+=t[3];const e=liveEvents[Math.floor(Math.random()*liveEvents.length)];S.rep+=e[2];S.fans+=e[3];showResult(`📱 ${t[0]}`,`${e[0]} : ${e[1]}`,()=>hub());});}
function party(){useActivity('Soirée',()=>{const e=partyEvents[Math.floor(Math.random()*partyEvents.length)];S.rep+=e[2];S.conf+=e[3];fatigue+=4;showResult('🎉 Soirée',e[0]+' : '+(e[1]||''),()=>hub());});}
function vacation(){useActivity('Vacances',()=>{const e=vacationEvents[Math.floor(Math.random()*vacationEvents.length)];S.conf+=e[2];S.rep+=e[3];fatigue=Math.max(0,fatigue-15);showResult('✈️ Vacances',e[0]+' : '+e[1],()=>hub());});}
function showResult(title,text,next){hideAll();$('result').classList.remove('hide');$('resultTitle').textContent=title;$('resultText').textContent=text;$('resultNext').onclick=next;}
function nextMonth(){month++;activities=0;fatigue=Math.max(0,fatigue-18);if(month>12){month=1;age++;}render();randomEvent();}
function randomEvent(){const pool=[];randomSeeds.forEach((s,i)=>pool.push({id:'r'+i,title:'🎲 '+s[0],text:s[1],rep:s[2],conf:s[3]}));trainingEvents.forEach((s,i)=>pool.push({id:'t'+i,title:'🏋️ '+s[0],text:s[1],rep:s[2],conf:s[3]}));liveEvents.forEach((s,i)=>pool.push({id:'l'+i,title:'📱 '+s[0],text:s[1],rep:s[2],fans:s[3]}));partyEvents.forEach((s,i)=>pool.push({id:'p'+i,title:'🎉 '+s[0],text:s[1],rep:s[2],conf:s[3]}));vacationEvents.forEach((s,i)=>pool.push({id:'v'+i,title:'✈️ '+s[0],text:s[1],conf:s[2],rep:s[3]}));if(P.origin==='Quartier')pool.push({id:'crime',title:'🚨 Ton passé revient',text:'Une ancienne connaissance veut te rapprocher d’un réseau criminel. Une mauvaise décision peut mettre fin à ta carrière.',rep:0,conf:-10,crime:true});const available=pool.filter(e=>!usedEvents.has(e.id));const e=available.length?available[Math.floor(Math.random()*available.length)]:pool[Math.floor(Math.random()*pool.length)];usedEvents.add(e.id);hideAll();$('event').classList.remove('hide');$('eventTitle').textContent=e.title;$('eventText').textContent=e.text;$('eventChoices').innerHTML=`<button class="choice" id="eventGood">Faire le bon choix</button><button class="choice" id="eventRisk">Prendre un risque</button>`;$('eventGood').onclick=()=>eventChoice(e,false);$('eventRisk').onclick=()=>eventChoice(e,true);}
function eventChoice(e,risk){if(e.crime&&risk){endCareer('🚨 Tu as été arrêté à la suite de cette affaire. Ta carrière sportive est terminée.');return}S.rep+=(e.rep||0)+(risk?3:0);S.conf+=(e.conf||0)+(risk?2:0);S.fans+=(e.fans||0)+(risk?500:100);if(risk&&Math.random()<.12)fatigue+=10;render();showResult(e.title,risk?'Ton choix risqué paie cette fois.':'Ton choix prudent renforce ton image.',()=>hub());}
function match(){hideAll();$('match').classList.remove('hide');let fatiguePenalty=Math.max(0,Math.floor((fatigue-45)/5));let base=Math.max(20,S.skill-fatiguePenalty);$('matchText').textContent=fatigue>60?`Tu es très fatigué. Tes performances peuvent chuter de ${fatiguePenalty} points.`:`État physique correct. Forme : ${base}.`;$('matchChoices').innerHTML=['Jeu agressif','Jeu équilibré','Jeu sécurisé'].map((x,i)=>`<button class="choice" data-play="${i}">${x}</button>`).join('');}
function play(i){const fatiguePenalty=Math.max(0,Math.floor((fatigue-45)/5));const result=Math.max(0,S.skill-fatiguePenalty)+(i===0?10:i===1?6:2)+Math.floor(Math.random()*12);S.rep+=result>70?10:result>55?5:1;S.coach+=result>70?7:result>55?3:-2;S.fans+=result*20;fatigue+=12;matchNo++;render();showResult(result>70?'🏆 Match exceptionnel':result>55?'🔥 Bonne performance':'😬 Match compliqué',`Note de performance : ${result}/100. Fatigue : ${fatigue}.`,()=>hub());}
function showOffers(){hideAll();$('offers').classList.remove('hide');if(offers.length===0&&S.rep>=70){offers=[...colleges].slice(0,Math.min(5,Math.floor(S.rep/25)-1));}$('offerList').innerHTML=offers.length?offers.map((x,i)=>`<button class="choice" data-offer="${i}">🎓 ${x} · offre de bourse</button>`).join(''):'Aucune offre pour le moment. Travaille tes performances et ta réputation.';}
function acceptOffer(i){const c=offers[i];S.college=colleges.indexOf(c)+1;S.coach+=8;S.rep+=5;showResult('🎓 Offre acceptée',`Tu choisis ${c}. Les recruteurs suivront ta progression.`,()=>hub());}
function draftCheck(){hideAll();$('draft').classList.remove('hide');const eligible=age>=21&&S.rep>=130&&S.coach>=85; $('draftText').textContent=age<21?'Tu dois encore progresser avant la Draft.':eligible?'Les scouts NFL sont très intéressés. Tu peux entrer dans la Draft.':'Tu es éligible en âge, mais tes performances ne suffisent pas encore.';$('draftBtn').onclick=()=>{if(!eligible){hub();return}const round=Math.max(1,Math.min(7,8-Math.floor(S.rep/35)));showResult('🏈 DRAFT NFL',`🎉 ${P.first} ${P.last} est sélectionné au ${round}e tour ! Une équipe NFL mise sur lui.`,()=>hub());};}
function endCareer(t){state.careerOver=true;hideAll();$('over').classList.remove('hide');$('overText').textContent=t;try{localStorage.removeItem('rtnfl-save')}catch(e){}}
$('creator').addEventListener('input',e=>{if(e.target.id==='height')$('heightVal').textContent=(+e.target.value/100).toFixed(2)+' m';if(e.target.id==='weight')$('weightVal').textContent=e.target.value+' kg';});
$('startBtn').onclick=start;$('trainBtn').onclick=trainingMenu;$('dateBtn').onclick=date;$('partyBtn').onclick=party;$('liveBtn').onclick=livestreamMenu;$('vacationBtn').onclick=vacation;$('matchBtn').onclick=match;$('monthBtn').onclick=nextMonth;$('offersBtn').onclick=showOffers;$('draftMenuBtn').onclick=draftCheck;$('activityChoices').addEventListener('click',e=>{if(e.target.dataset.train)train(+e.target.dataset.train);if(e.target.dataset.live)live(+e.target.dataset.live)});$('matchChoices').addEventListener('click',e=>{if(e.target.dataset.play)play(+e.target.dataset.play)});$('offerList').addEventListener('click',e=>{if(e.target.dataset.offer)acceptOffer(+e.target.dataset.offer)});$('continueBtn').onclick=hub;
if(load()){hideAll();$('career').classList.remove('hide');render();hub();}
